-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `primeiroNome` VARCHAR(45) NULL,
  `segundoNome` VARCHAR(45) NULL,
  `sobreNome` VARCHAR(45) NULL,
  `dataNascimento` DATE NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(8) NULL,
  `municipio` VARCHAR(45) NULL,
  `uf` VARCHAR(2) NULL,
  `pais` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `celular` VARCHAR(11) NULL,
  `telefone` VARCHAR(10) NULL,
  `tipoCliente` CHAR(1) NULL,
  `cnpj` VARCHAR(11) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entrega` (
  `identrega` INT NOT NULL,
  `status` CHAR(1) NULL,
  `rastreio` VARCHAR(45) NULL,
  `idPedido` VARCHAR(45) NULL,
  PRIMARY KEY (`identrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estoque` (
  `idestoque` INT NOT NULL,
  `local` VARCHAR(45) NULL,
  PRIMARY KEY (`idestoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `idfornecedor` INT NOT NULL,
  `razao_social` VARCHAR(45) NULL,
  `nomeFantasia` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(8) NULL,
  `municipio` VARCHAR(45) NULL,
  `uf` VARCHAR(2) NULL,
  `pais` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `celular` VARCHAR(11) NULL,
  `telefone` VARCHAR(10) NULL,
  PRIMARY KEY (`idfornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `idpagamento` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `numeroCartao` VARCHAR(15) NULL,
  `cartaoValidade` VARCHAR(5) NULL,
  `cartaoCvv` INT(3) NULL,
  `total` FLOAT NULL,
  `pedido_idpedido` INT NOT NULL,
  `pedido_cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idpagamento`),
  INDEX `fk_pagamento_pedido1_idx` (`pedido_idpedido` ASC, `pedido_cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_pedido1`
    FOREIGN KEY (`pedido_idpedido` , `pedido_cliente_idcliente`)
    REFERENCES `mydb`.`pedido` (`idpedido` , `cliente_idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `idpedido` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `codigoRastreio` VARCHAR(45) NULL,
  `valorFrete` FLOAT NULL,
  `pagamentoBoleto` INT NULL,
  `cliente_idcliente` INT NOT NULL,
  `entrega_identrega` INT NOT NULL,
  PRIMARY KEY (`idpedido`, `cliente_idcliente`, `entrega_identrega`),
  INDEX `fk_pedido_cliente_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_pedido_entrega1_idx` (`entrega_identrega` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_entrega1`
    FOREIGN KEY (`entrega_identrega`)
    REFERENCES `mydb`.`entrega` (`identrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `idproduto` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto_estoque` (
  `idproduto_estoque` INT NOT NULL,
  `quantidade` INT NULL,
  `produto_idproduto` INT NOT NULL,
  `estoque_idestoque` INT NOT NULL,
  PRIMARY KEY (`idproduto_estoque`, `produto_idproduto`, `estoque_idestoque`),
  INDEX `fk_produto_estoque_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  INDEX `fk_produto_estoque_estoque1_idx` (`estoque_idestoque` ASC) VISIBLE,
  CONSTRAINT `fk_produto_estoque_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_estoque_estoque1`
    FOREIGN KEY (`estoque_idestoque`)
    REFERENCES `mydb`.`estoque` (`idestoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto_fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto_fornecedor` (
  `idproduto_fornecedor` INT NOT NULL,
  `quantidade` INT NULL,
  `produto_idproduto` INT NOT NULL,
  `fornecedor_idfornecedor` INT NOT NULL,
  PRIMARY KEY (`idproduto_fornecedor`, `produto_idproduto`, `fornecedor_idfornecedor`),
  INDEX `fk_produto_fornecedor_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  INDEX `fk_produto_fornecedor_fornecedor1_idx` (`fornecedor_idfornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_produto_fornecedor_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_fornecedor_fornecedor1`
    FOREIGN KEY (`fornecedor_idfornecedor`)
    REFERENCES `mydb`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto_pedido` (
  `idproduto_pedido` INT NOT NULL,
  `quantidade` INT NULL,
  `status` VARCHAR(45) NULL,
  `valorUnitario` FLOAT NULL,
  `dataPedido` DATE NULL,
  `pedido_idpedido` INT NOT NULL,
  `pedido_cliente_idcliente` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`idproduto_pedido`, `pedido_idpedido`, `pedido_cliente_idcliente`, `produto_idproduto`),
  INDEX `fk_produto_pedido_pedido1_idx` (`pedido_idpedido` ASC, `pedido_cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_produto_pedido_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_pedido_pedido1`
    FOREIGN KEY (`pedido_idpedido` , `pedido_cliente_idcliente`)
    REFERENCES `mydb`.`pedido` (`idpedido` , `cliente_idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_pedido_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto_venda_terceiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto_venda_terceiro` (
  `idproduto_venda_terceiro` INT NOT NULL,
  `quantidade` INT NULL,
  `produto_idproduto` INT NOT NULL,
  `vendedor_terceiro_idterceiro_vendedor` INT NOT NULL,
  PRIMARY KEY (`idproduto_venda_terceiro`, `produto_idproduto`, `vendedor_terceiro_idterceiro_vendedor`),
  INDEX `fk_produto_venda_terceiro_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  INDEX `fk_produto_venda_terceiro_vendedor_terceiro1_idx` (`vendedor_terceiro_idterceiro_vendedor` ASC) VISIBLE,
  CONSTRAINT `fk_produto_venda_terceiro_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_venda_terceiro_vendedor_terceiro1`
    FOREIGN KEY (`vendedor_terceiro_idterceiro_vendedor`)
    REFERENCES `mydb`.`vendedor_terceiro` (`idterceiro_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendedor_terceiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendedor_terceiro` (
  `idterceiro_vendedor` INT NOT NULL,
  `razao_social` VARCHAR(45) NULL,
  `nomeFantasia` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(8) NULL,
  `municipio` VARCHAR(45) NULL,
  `uf` VARCHAR(2) NULL,
  `pais` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `celular` VARCHAR(11) NULL,
  `telefone` VARCHAR(10) NULL,
  PRIMARY KEY (`idterceiro_vendedor`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
